import { randomUUID } from "node:crypto";
import type { JsonFileMemoryStore } from "./store.js";
import { rank } from "./retrieval.js";
import type { MemoryFilter, MemoryInput, MemoryRecord, MemoryStats, SearchOptions, SearchResult } from "./types.js";
import { MEMORY_SCOPES } from "./types.js";
function assertInput(input: MemoryInput): void { if (!input.content?.trim()) throw new Error("memory content is required"); if (input.content.length > 100_000) throw new Error("memory content exceeds 100000 characters"); if (input.confidence !== undefined && (input.confidence < 0 || input.confidence > 1)) throw new Error("confidence must be between 0 and 1"); }
function applies(record: MemoryRecord, filter: MemoryFilter): boolean { return (!filter.scope || record.scope === filter.scope) && (!filter.projectId || record.projectId === filter.projectId) && (!filter.sessionId || record.sessionId === filter.sessionId) && (!filter.userId || record.userId === filter.userId) && (!filter.type || record.type === filter.type) && (!filter.tags || filter.tags.every((tag) => record.tags.includes(tag))); }
export class MemoryEngine {
 constructor(private readonly store: JsonFileMemoryStore) {}
 async add(input: MemoryInput): Promise<MemoryRecord> { assertInput(input); const now = new Date().toISOString(); const record: MemoryRecord = { id: randomUUID(), content: input.content.trim(), type: input.type ?? "NOTE", scope: input.scope ?? "PROJECT", userId: input.userId, projectId: input.projectId, sessionId: input.sessionId, source: input.source ?? "manual", confidence: input.confidence ?? 0.8, createdAt: now, updatedAt: now, tags: [...new Set(input.tags ?? [])], metadata: input.metadata ?? {} }; const all = await this.store.load(); all.push(record); await this.store.save(all); return record; }
 async upsert(input: MemoryInput): Promise<MemoryRecord> { assertInput(input); const all = await this.store.load(); const found = all.find((item) => item.content === input.content.trim() && item.projectId === input.projectId && item.scope === (input.scope ?? "PROJECT")); if (!found) return this.add(input); return this.update(found.id, input); }
 async get(id: string): Promise<MemoryRecord | undefined> { const all = await this.store.load(); const found = all.find((item) => item.id === id); if (found) { found.lastAccessedAt = new Date().toISOString(); await this.store.save(all); } return found; }
 async list(filter: MemoryFilter = {}): Promise<MemoryRecord[]> { return (await this.store.load()).filter((record) => applies(record, filter)); }
 async search(query: string, options: SearchOptions = {}): Promise<SearchResult[]> { if (!query.trim()) return []; const all = await this.store.load(); const results = rank(all, query, options); const accessed = new Date().toISOString(); for (const result of results) result.record.lastAccessedAt = accessed; if (results.length) await this.store.save(all); return results; }
 async update(id: string, patch: Partial<MemoryInput>): Promise<MemoryRecord> { if (patch.content !== undefined) assertInput({ content: patch.content, confidence: patch.confidence }); const all = await this.store.load(); const index = all.findIndex((item) => item.id === id); if (index < 0) throw new Error(`memory not found: ${id}`); const old = all[index]; const next = { ...old, ...patch, content: patch.content?.trim() ?? old.content, tags: patch.tags ? [...new Set(patch.tags)] : old.tags, metadata: patch.metadata ? { ...old.metadata, ...patch.metadata } : old.metadata, updatedAt: new Date().toISOString() }; all[index] = next; await this.store.save(all); return next; }
 async delete(id: string): Promise<boolean> { const all = await this.store.load(); const next = all.filter((item) => item.id !== id); if (next.length === all.length) return false; await this.store.save(next); return true; }
 async clear(filter: MemoryFilter = {}): Promise<number> { const all = await this.store.load(); const next = all.filter((item) => !applies(item, filter)); await this.store.save(next); return all.length - next.length; }
 async count(filter: MemoryFilter = {}): Promise<number> { return (await this.list(filter)).length; }
 async stats(): Promise<MemoryStats> { const all = await this.store.load(); const byScope = Object.fromEntries(MEMORY_SCOPES.map((scope) => [scope, 0])) as MemoryStats["byScope"]; const byType: MemoryStats["byType"] = {}; for (const record of all) { byScope[record.scope]++; byType[record.type] = (byType[record.type] ?? 0) + 1; } return { count: all.length, byScope, byType }; }
 async export(): Promise<MemoryRecord[]> { return this.store.load(); }
 async import(records: MemoryRecord[], mode: "merge" | "replace" = "merge"): Promise<number> { if (!Array.isArray(records)) throw new Error("import must be an array"); const existing = mode === "replace" ? [] : await this.store.load(); const ids = new Set(existing.map((item) => item.id)); for (const record of records) { assertInput(record); if (!ids.has(record.id)) { existing.push(record); ids.add(record.id); } } await this.store.save(existing); return existing.length; }
 async backup(destination: string): Promise<void> { await this.store.backup(destination); }
 async restore(source: string): Promise<void> { await this.store.restore(source); }
 async health() { return this.store.health(); }
}
