#!/usr/bin/env node
import { homedir } from "node:os"; import { resolve } from "node:path"; import { readFile, writeFile } from "node:fs/promises";
import { JsonFileMemoryStore, MemoryEngine, defaultMemoryPath, resolveProjectIdentity } from "../../core/src/index.js";
import { runStdioServer } from "../../process-bridge/src/index.js";
function usage(): never { console.error("Usage: local-memory <init|add|search|get|delete|list|clear|export|import|backup|restore|stats|doctor|stdio> [arguments] [--project ID] [--file PATH]"); process.exit(2); }
function option(args: string[], name: string): string | undefined { const i = args.indexOf(name); return i >= 0 ? args[i + 1] : undefined; }
async function main(): Promise<void> { const args = process.argv.slice(2); const command = args.shift(); if (!command) usage(); const root = resolve(option(args, "--root") ?? process.cwd()); const identity = await resolveProjectIdentity(root, option(args, "--project")); const file = resolve(option(args, "--file") ?? defaultMemoryPath(homedir(), identity.id)); const engine = new MemoryEngine(new JsonFileMemoryStore(file)); const positional = args.filter((a, i) => a !== "--root" && a !== "--project" && a !== "--file" && args[i - 1] !== "--root" && args[i - 1] !== "--project" && args[i - 1] !== "--file"); switch (command) { case "init": await engine.health(); print({ project: identity, file, modified: true }); break; case "add": print(await engine.add({ content: positional.join(" "), projectId: identity.id, type: (option(args, "--type") as never) ?? "NOTE", scope: (option(args, "--scope") as never) ?? "PROJECT", source: "cli", tags: option(args, "--tags")?.split(",").filter(Boolean) })); break; case "search": print(await engine.search(positional.join(" "), { projectId: identity.id, limit: Number(option(args, "--limit") ?? 10) })); break; case "get": print(await engine.get(positional[0] ?? "")); break; case "delete": print({ deleted: await engine.delete(positional[0] ?? ""), modified: true }); break; case "list": print(await engine.list({ projectId: identity.id })); break; case "clear": print({ deleted: await engine.clear({ projectId: identity.id }), modified: true }); break; case "export": { const destination = required(positional[0], "export destination"); await writeFile(destination, `${JSON.stringify(await engine.export(), null, 2)}\n`); print({ destination, modified: true }); break; } case "import": { const source = required(positional[0], "import source"); print({ records: await engine.import(JSON.parse(await readFile(source, "utf8")), "merge"), modified: true }); break; } case "backup": { const destination = required(positional[0], "backup destination"); await engine.backup(destination); print({ destination, modified: true }); break; } case "restore": { const source = required(positional[0], "restore source"); await engine.restore(source); print({ source, modified: true }); break; } case "stats": print(await engine.stats()); break; case "doctor": print({ project: identity, storage: await engine.health(), runtime: { node: process.version, platform: process.platform, networkRuntime: false } }); break; case "stdio": runStdioServer(engine); break; default: usage(); } }
function required(value: string | undefined, label: string): string { if (!value) throw new Error(`${label} is required`); return value; } function print(value: unknown): void { process.stdout.write(`${JSON.stringify(value, null, 2)}\n`); }
main().catch((error) => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; });
